name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  
jobs:
  terraform:
    name: 'Terraform'
    env:
    #AWS Secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEYID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETACCESSKEY }}
    runs-on: ubuntu-latest
    environment: production
    steps:

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        # The path to the Terraform configuration files
        tf_actions_version: 1.6.6
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true

    - name: Terraform plan
      uses: hashicorp/terraform-github-actions@master
      with:
        # The path to the Terraform configuration files
        tf_actions_version: v1.11.4
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
    
    - name: Terraform apply
      uses: hashicorp/terraform-github-actions@master
      with:
        # The path to the Terraform configuration files
        tf_actions_version: v1.11.4
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: '.'
        tf_actions_comment: true

